//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieteMenBon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("231, 149, 86")]
        public global::System.Drawing.Color defaultOrangeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["defaultOrangeBackColor"]));
            }
            set {
                this["defaultOrangeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("167, 207, 73")]
        public global::System.Drawing.Color defaultGreenBackColor {
            get {
                return ((global::System.Drawing.Color)(this["defaultGreenBackColor"]));
            }
            set {
                this["defaultGreenBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IndianRed")]
        public global::System.Drawing.Color defaultIndiaRedBackColor {
            get {
                return ((global::System.Drawing.Color)(this["defaultIndiaRedBackColor"]));
            }
            set {
                this["defaultIndiaRedBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("198, 80, 90")]
        public global::System.Drawing.Color selectedIndiaBackColor {
            get {
                return ((global::System.Drawing.Color)(this["selectedIndiaBackColor"]));
            }
            set {
                this["selectedIndiaBackColor"] = value;
            }
        }
    }
}
